export const termsPage = {
  tabTitle: "Terms and Conditions, South Africa, Zookini Tours",
  description: "Zookini Tours Terms and Conditions: reservations, payment, cancellations, change of plans and insurance.",
  eyebrow: "Policies",
  title: "Terms and Conditions",
  lede: "Please read these Terms and Conditions before you confirm a booking.",
  blocks: [
    { kind: "p", text: "The confirmation of a booking for a chosen tour/accommodation/holiday is regarded as a contract between the client and the Tour Operator ZOOKINI TOURS, in which the client agrees to the terms and conditions set out therein." },
    { kind: "h2", text: "Confirmation of a Reservation and Entering Into a Contract" },
    { kind: "li", text: "Upon confirmation of a reservation, ZOOKINI TOURS will immediately request a 50% non-repayable deposit of the total price for a chosen tour/accommodation." },
    { kind: "li", text: "The contract comes into effect as soon as the deposit payment is received." },
    { kind: "li", text: "Up until that point, the correspondence between ZOOKINI TOURS and the client is treated as a quotation, subject to price increases and the availability of the option being quoted for." },
    { kind: "li", text: "Please note that ZOOKINI TOURS quotes the full price for the tour/accommodation only as a lump sum. Clients will not be given individual prices of accommodation and / or performances on offer." },
    { kind: "h2", text: "Payment" },
    { kind: "p", text: "The balance of the total price for reserved tour/accommodation/holiday needs to reach ZOOKINI TOURS six (6) weeks before the departure date of the tour/holiday, or date of the reserved services and / or performances. The necessary travel documents will be sent by e-mail or courier. Please mail proof of the EFT payment to ZOOKINI TOURS." },
    { kind: "h2", text: "Choice of Law" },
    { kind: "p", text: "All legal relationships under this contract shall be governed by and construed in accordance with the South African law applicable where ZOOKINI TOURS has its registered legal domicile." },
    { kind: "h2", text: "Cancellations" },
    { kind: "p", text: "A cancellation of a reservation must be in writing. Please note that, upon receipt of the cancellation by ZOOKINI TOURS, the following shall apply:" },
    { kind: "li", text: "In respect of a cancellation up to 41 days prior to the departure date: 25% deposit shall be forfeited," },
    { kind: "li", text: "In respect of a cancellation from 40 days to 14 days prior to departure: 50% of the total price of the tour/accommodation shall be forfeited." },
    { kind: "li", text: "In respect of a cancellation thirteen days or less prior to departure: 100% of the total price of the tour/accommodation shall be forfeited." },
    { kind: "h2", text: "Change of Plans" },
    { kind: "p", text: "No refunds will be made for a change of itinerary during the trip or for services reserved but not utilised. Clients should be insured for such instances. ZOOKINI TOURS will charge R1 000 (subject to change) for every amendment and/or change to an already confirmed booking in addition to the cost to the new arrangements made." },
    { kind: "h2", text: "Insurance and Liability" },
    { kind: "li", text: "All ZOOKINI TOURS clients are requested to take out travel and cancellation insurance. ZOOKINI TOURS also urges clients to consider taking out insurance for their health and safety, their luggage and their money." },
    { kind: "li", text: "ZOOKINI TOURS will not accept any liability for death, injury, illness, damage and / or financial loss incurred by the client on a tour or at the chosen accommodation establishment. ZOOKINI TOURS shall take due care in the conduct of its business in respect of: the preparations made for each tour or reservation, the correctness of each itinerary, the selection and supervision of services rendered by others, the proper execution of its duties as specified in the Contract. ZOOKINI TOURS shall not be held liable for any inadequacies in the services rendered by others. Although ZOOKINI TOURS undertakes to ensure that clients are kept out of harm's way at all times, clients are ultimately responsible for taking due care of their own health and safety." },
    { kind: "h2", text: "Drivers' Licences" },
    { kind: "p", text: "It is the responsibility of the client who undertakes a Self-Drive Tour in Southern Africa to obtain a valid Driver's Licence before commencing his / her journey. Please note that the licence of the client's country of origin is also required from the car rental company." },
    { kind: "h2", text: "Visas, Customs Regulations and Health Regulations" },
    { kind: "p", text: "The client shall be responsible for ensuring he or she obtains the necessary visas for the country or countries to be visited. It shall also be the clients' responsibility to familiarise themselves with the customs regulations of the country / countries concerned. Furthermore, the responsibility shall rest with the client to ensure he or she is medically fit to travel, which includes complying with the health regulations of the country / countries concerned. Prior to their departure, clients should consult a medical professional regarding the recommended anti-malaria precautions. Anti-malaria medication can be obtained in Namibia, South Africa and Zimbabwe." },
    { kind: "h2", text: "Booking Conditions" },
    { kind: "p", text: "Minimum of 12 Persons per tour on every tour. Maximum of 16 Persons per tour on the Woman & Wine Weekend, Life is Art Tour, Protea & Fynbos Tour and Time to Taste Foodie Tour. Maximum of 52 Persons per tour on the I Love Cape Town Tour, Wondrous West Coast Tour, Glorious Garden Route Tour, Overwhelming Overberg Tour and Bushveld Safari Adventure Tour. Maximum of 60 Persons per tour on the Drakensberg Adventure Tour. The Woman & Wine Weekend is Woman only." },
  ],
} as const;

export type TermsBlock = (typeof termsPage.blocks)[number];
